### PR TITLE
Don't close the text form when click on the textbox

### LINKED ISSUE #508: Too easy to close the text sprite input
### Expected Behavior

When entering text for a text sprite the user should be able to change the text size and color without closing the input accidentally. If you are trying to tap one of the controls, but miss the target and end up tapping the blue background, the input should not close. If you tap outside the blue background it should close.

### Actual Behavior

If you tap inside the text input controls on a blue area, the input closes.

### Steps to Reproduce

1. Tap the 'abc' button to open the text input
2. Tap to the side of one of the controls (size,color)
3. Text input closes

### Device and Operating System
iPad mini 4 iOS 13.5

### PR DESCRIPTION
**Pull request by yueyuzhao**
### Resolves

- Resolves #508 

### Proposed Changes

Ignore the events when touch/click on the textbox

### Reason for Changes

When editing or creating text sprite, the text box will be closed if the user clicked on the blue area.

### Test Coverage

- [x] iPad mini 2 (iOS 12.5.1)
- [x] Kindle Fire HD 8 (Android 5.1)

### CODE REVIEW

File: src/editor/ui/UI.js [hunk 1]
```diff
@@ -952,11 +952,14 @@ export default class UI {
     static createFormForText (p) {
         var tf = newHTML('div', 'pagetext off', p);
         tf.setAttribute('id', 'textbox');
-        if (isAndroid) {
-            tf.onmousedown = function (e) {
-                e.preventDefault();
-            };
-        }
+        // If the textbox is click or touched, the input may lost focus,
+        // and it may cause the text form miss closed.
```
Comment (chrisgarrity) [inline src/editor/ui/UI.js:956]:
```suggestion
        // If the textbox background is clicked or touched, the input loses focus,
        // which causes the text input to close unexpectedly 
```
Just a suggestion for the comment.

File: src/editor/ui/UI.js [hunk 2]
```diff
@@ -952,11 +952,14 @@ export default class UI {
     static createFormForText (p) {
         var tf = newHTML('div', 'pagetext off', p);
         tf.setAttribute('id', 'textbox');
-        if (isAndroid) {
```
Comment (chrisgarrity) [inline src/editor/ui/UI.js:955]: Interesting that it was only a bug on iOS because we had this code for Android!

**Review by chrisgarrity — APPROVED** [review]
Just a suggestion for rewording the comment, otherwise everything's great.
