### PR TITLE
Fix clone svg element null pointer

### LINKED ISSUE #499: Filling a shape with the camera should not change the effect of the stamp tool
### Expected Behavior

After using the stamp tool, the character should be duplicated, and the select (arrow) tool should be active. Nothing should be pre-selected.

### Actual Behavior
If you fill with a color, it behaves as expected. In the video, when Dot's hair is filled with red, stamp automatically switches to the arrow tool, and the character is duplicated. When the hair is filled with the camera, and then the stamp tool is used to duplicate the character, the stamp tool remains selected. After manually switching to the arrow tool, at first both copies are selected, but tapping again selects the top one and it can be moved separately.

https://user-images.githubusercontent.com/399209/130504823-291fc6b9-2cda-4c05-95bb-8bcebe4ccf93.mp4

### Steps to Reproduce

1. Edit a character in the paint editor (Dot for example)
2. Tap the camera tool, then tap a shape to fill with the camera
3. Camera input opens - take a picture (switching front/back camera works fine)
4. In paint editor, select the stamp tool, and touch the character to duplicate
5. Note that stamp tool is still active (touching the character again will duplicate again, and again...)
6. Switch to the arrow tool, notice that part of the character is already selected, touching the character moves both copies. 
7. Tap outside the character to deselect  everything, then tap on the top layer, the duplicated copy can be moved separately

### Device and Operating System

confirmed on Android and iOS.

### PR DESCRIPTION
**Pull request by yueyuzhao**
### Resolves

- Resolves #499 
- Resolves https://github.com/LLK/scratchjr-private/issues/646

### Proposed Changes

Skip to continue processing null element.

### Reason for Changes

Sometimes the cloned element is null and should not be processed.

### Test Coverage

- [x] iPad mini 2 (iOS 12.5.2) 
- [x] SM T280 (Android 5.1.1)
- [x] Kindle Fire HD 8 (Android 5.1)

### CODE REVIEW

File: src/painteditor/SVGTools.js [hunk 1]
```diff
@@ -805,6 +805,9 @@ export default class SVGTools {
             var g = SVGTools.createGroup(p, getIdFor('group'));
             for (var i = 0; i < elem.childElementCount; i++) {
                 var shape = SVGTools.getClonedElement(g, elem.childNodes[i]);
+                if (!shape) {
+                    continue;
```
Comment (chrisgarrity) [inline src/painteditor/SVGTools.js:809]: Usually, I'd try to write the code to avoid using "continue", but looking at the rest of SVGTools, it doesn't really make sense to rewrite here when we use this pattern all over.

**Review by chrisgarrity — APPROVED** [review]
