### PR TITLE
robust improvement: fix invalid input

### LINKED ISSUE #509: Character freezes when changing move block to a negative number while running
### Expected Behavior

Character should not freeze. Even if it needs to stop execution, you should be able to drag the character.

### Actual Behavior

If you have a move block inside a repeat loop, you can tap on the number to change the value while it's running. If you change the number to a positive number everything is fine. As soon as you type a minus '-', the character freezes. You cannot drag the character (you can return to the lobby and re-enter the project). If the grid is turned on, the highlighted indices become 'NaN' when you type '-'

Also, the character is missing from the thumbnail when you return to the lobby

### Steps to Reproduce

1. Add a move right block, and connect a repeat-forever (red category)
2. Turn the grid on
2. tap the strip to start it running, the character starts moving to the right
3. change the number to a different positive number, everything keeps moving
4. try to change the number to a negative number, everything stops as soon as the '-' is touched, highlighted grid values are 'NaN'

### Device and Operating System

confirmed on both iOS and Android

### PR DESCRIPTION
**Pull request by yueyuzhao**
### Resolves

- Resolves #509 

### Proposed Changes

When the block argument needs a number, set it to 0 if it's invalid.

### Reason for Changes

When editing running blocks, the single `-` sign is not processed properly. 

### Test Coverage

- [x] iPad mini 2 (iOS 12.5)
- [x] Kindle Fire HD8 (Android 5.1)

### CODE REVIEW

**Comment by deepankarmalhan** [comment]
SJR-158

File: src/editor/blocks/BlockArg.js [hunk 1]
```diff
@@ -206,6 +206,9 @@ export default class BlockArg {
             return;
         }
         this.argValue = val;
+        if (this.argType == 'n' && isNaN(Number(val))) {
```
Comment (deepankarmalhan) [inline src/editor/blocks/BlockArg.js:209]: Why are we checking if a user enters the letter `n`?

Comment (deepankarmalhan) [reply src/editor/blocks/BlockArg.js:209]: Also does this if statement make sure we don't stop the execution midway and keeps things running with the value 0? Has this been tested to see it doesn't remove character thumbnail from the project in the lobby?

**Review by deepankarmalhan — CHANGES_REQUESTED** [review]

File: src/editor/blocks/BlockArg.js (hunk 1 above)
Comment (yueyuzhao) [reply src/editor/blocks/BlockArg.js:209]: > Why are we checking if a user enters the letter `n`?

`n` is an `argType`, we use `n` for `BlockArg` numbers

Comment (yueyuzhao) [reply src/editor/blocks/BlockArg.js:209]: > Also does this if statement make sure we don't stop the execution midway and keeps things running with the value 0? 

Yes

> Has this been tested to see it doesn't remove character thumbnail from the project in the lobby?

I'll have this tested tomorrow.

Comment (yueyuzhao) [reply src/editor/blocks/BlockArg.js:209]: I just tested this on the iOS simulator, the thumbnail of the project is generated fine.

**Review by deepankarmalhan — APPROVED** [review]
