### PR TITLE
Fixes the iOS scrolling problem

### LINKED ISSUE #217: Whole window scrolls when dragging blocks to another sprite
From Paula B.:
I was trying ScratchJr and I found the following iOS bug (due to changes in Safari):

1. create a  sequence of blocks on one sprite
2. Try to drag that sequence into the thumbnail of another sprite —> the whole windows scrolls.

The way we solve it in TurtleArt is just by adding the following line on the startup routine:

document.body.addEventListener('touchmove', function(e){e.preventDefault();}, {passive: false});

### PR DESCRIPTION
**Pull request by chrisgarrity**
fixes #217 
A Safari update introduced this bug where the whole window scrolls. 

Note I branched from the firebase changes, so this should probably merge after that. It's really just one commit (the last one).

### CODE REVIEW

File: src/editor/ScratchJr.js [hunk 1]
```diff
@@ -235,6 +235,11 @@ export default class ScratchJr {
         } else {
             window.onmouseup = undefined;
         }
+        document.body.addEventListener('touchmove',
```
Comment (paulkaplan) [inline src/editor/ScratchJr.js]: Try removing `.ontouchmove` above, since it shouldn't be needed. That may also eliminate some of the other passive warnings.

**Comment by paulkaplan** [comment]
LGTM, one comment about something to try.
