### PR TITLE
iOS: scroll up a little bit if the textbox is on the bottom half of the screen

### LINKED ISSUE #474: Text recolor/resize hidden by the soft keyboard
### Expected Behavior

You should be able to resize of recolor text on the stage.

### Actual Behavior

IMG_F2D6FA74DF99-1

If the text sprite is near the top of the stage the text customization controls (size/color) are visible. If the text sprite is near the bottom of the stage, the text input slides up out of the way of the soft keyboard. If the text is near the middle of the stage the input doesn't slide up, and the controls are hidden by the keyboard.
### Steps to Reproduce

on an iPad:

- tap 'ABC' button to add text 
- move the text sprite to approximately the middle of the stage
- tap the text sprite to reopen the input UI
- tap either the AAA, or bucket to open customization controls
### Device and Operating System

iPad mini 4, iOS 13.6.1
Note: doesn't happen on Android, input always slides up out of the sway of the keyboard.

### PR DESCRIPTION
**Pull request by yueyuzhao**
### Resolves

- Resolves #474 

### Proposed Changes

Scroll up if the bottom of textbox is on the bottom half of the screen

### Reason for Changes

On some specific position, the textbox for text sprites are not shown fully on iOS

### Test Coverage

- [x] iPad mini 2 (iOS 12.5.2)
- [x] iPad Pro 4th generation (12.9 inch) (iOS 14.1)

### CODE REVIEW

File: src/editor/engine/Sprite.js [hunk 1]
```diff
@@ -913,6 +913,13 @@ export default class Sprite {
                 me.unfocusText();
             });
         } else {
+            // On iOS if the bottom of the textbox is lower than half of the screen
+            // the color and font size menu may be covered by the keyboard
+            if (gn('textbox').offsetTop + gn('textbox').offsetHeight > WINDOW_INNER_HEIGHT / 2) {
```
Comment (chrisgarrity) [inline src/editor/engine/Sprite.js:918]: When the text box opens and it's right on the edge of the half way point, it doesn't scroll, so if you open the font or color menu they're still hidden by the keyboard. I think we need to adjust when the offset is more than 45% of the height.

**Review by chrisgarrity — CHANGES_REQUESTED** [review]
I left a suggestion that we start scrolling at about 45% of the height instead of 50%. I tried that, and it seemed ok. There may be a better value between 45-50%, but I'm not sure it's worth a lot of time trying different values.

**Review by chrisgarrity — APPROVED** [review]
💯 looks good
